### ISSUE TITLE
Bug in BB indicator

### ISSUE THREAD

**Issue by dungnt109** [deathlyface/python-tradingview-ta#37] opened 2021-03-30 15:06 UTC
Hi, 

I spot a bug at line 25 of the main.py file. 
```
        if indicator_values[26] != None:
            computed_oscillators["BBP"] = Compute.Simple(indicator_values[26])
            oscillators_counter[computed_oscillators["BBP"]] += 1
```

It should be 

`            computed_oscillators["BBP"] = Compute.BBP(indicator_values[26])
`

https://github.com/deathlyface/python-tradingview-ta/blob/0cf4a87a244dc5116639936f783608955fed7653/tradingview_ta/main.py#L245

**Comment by deathlyface** [comment] 2021-03-31 06:23
Hello @dungnt109,

It's not a bug. If you look closely at tradingview's [JS code](https://gist.githubusercontent.com/deathlyface/f0bb91658c1f161cafe8990db1473bd6/raw/3dfd3f41774eed8e389b010dec1488fe17474039/technicals.1f7162801b978b271886.js) and [technicals.py](https://github.com/deathlyface/python-tradingview-ta/blob/main/tradingview_ta/technicals.py), there's no `Compute.BBP` function. TradingView uses the simple compute to compute the BBP.

**Comment by deathlyface** [comment] 2021-03-31 06:35
I'll close this issue. If you have any questions, don't hesitate to ask me. Have a nice day.

**Closed by deathlyface** 2021-03-31 06:35 UTC
